server.port=8886
logging.config=classpath:log4j2-spring.xml
spring.application.name=corgiWorker
spring.dubbo.registry=zookeeper://47.111.180.175:2181
spring.redis.host=r-uf6607cugmtd0glbje.redis.rds.aliyuncs.com
spring.redis.port=6379
spring.redis.password=Corgi2020
spring.rabbitmq.host=172.19.22.140
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin
spring.rabbitmq.listener.simple.concurrency=10
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-attempts=5
spring.rabbitmq.listener.simple.retry.initial-interval=5000
spring.rabbitmq.virtual-host=/test
push.masterSecret=41d8dfccbb083abe282f00bd
push.appKey=6fe45cad76b08c480e10b31a