
server.port = 8886
logging.config = classpath:log4j2-spring.xml

spring.application.name=corgiWorker
spring.dubbo.registry=zookeeper://127.0.0.1:2181
spring.redis.host=localhost
spring.redis.port=6379

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
# 开启ACK
spring.rabbitmq.listener.direct.acknowledge-mode=manual
spring.rabbitmq.listener.simple.acknowledge-mode=manual

push.masterSecret=41d8dfccbb083abe282f00bd
push.appKey=6fe45cad76b08c480e10b31a